### PR TITLE
Performance Improvements

### PR DESCRIPTION
**Pull request by evanlouie**
- Table now defaults to only displaying 50 rows. Is configurable by passing a
  `limit` GET parameter (e.g. `?limit=100`).
- Removed unnecessary calls to `history.replaceState` when search params are
  identical.
- Optimized numerous array conversions.
- Removed usage of `querystring` in front-end code and replace with
  `URLSearchParams` instances.
- Optimized `getAuthors` to only dispatch 1 request per unique author.

Fixes https://github.com/microsoft/bedrock/issues/1335

### CODE REVIEW

**Comment by evanlouie** [comment]
@samiyaakhtar I've rebased this off your refactor branch -- we can merge after your branch has been merged

**Comment by samiyaakhtar** [comment]
@evanlouie thanks Evan! Merging now

**Comment by samiyaakhtar** [comment]
Oh wait, first need to be unblocked on https://github.com/microsoft/spektate/pull/105 @andrebriggs

**Comment by evanlouie** [comment]
Abandoning do to being annoying to rebase. Submitting new PR based on master

**Pull request closed without merging**
