### PR TITLE
Cluster column in dashboard

### PR DESCRIPTION
**Pull request by samiyaakhtar**
Opening this PR to start getting early feedback on the UI. 

- Added a column that shows up only when there is cluster information to show
- Refactored some code in fetch author

Screen Shot 2020-01-15 at 4 03 28 PM

Screen Shot 2020-01-15 at 4 06 33 PM

Closes https://github.com/microsoft/bedrock/issues/840

### CODE REVIEW

**Comment by gemorris** [comment]
The column/cell/truncation is great.

 The tooltip is serviceable, I'd prefer to have stacked content as in the mockup, for scanability. This however is certainly good enough to ship as-is.

**Comment by andrebriggs** [comment]
@samiyaakhtar is the `and 1 more...` a hyperlink? If so what happens when you click on it?

Also in the 1st screenshot there is a lot of whitespace on right of the cluster column. Is that on purpose?

**Comment by samiyaakhtar** [comment]
@gemorris I just made an update to add new lines between regions in the tooltip. 

Screen Shot 2020-01-16 at 2 19 59 PM

@andrebriggs yes, it's a hyperlink which takes you to the releases page [such as this one](https://github.com/samiyaakhtar/hello-bedrock-manifest/releases), where all tag information is available. 
The whitespace is not on purpose, I was testing on a really large monitor so there was a lot of room remaining in the table to the right.

**Comment by gemorris** [comment]
Looks great!

**Comment by samiyaakhtar** [comment]
@gemorris @andrebriggs Here's the UI update we discussed today:

- Made the links subtle
- Made the author and cluster fonts regular
- Added tooltip and link regardless of if there is an overflow in the cluster column

Screen Shot 2020-01-21 at 2 46 51 PM

**Pull request merged**
