### PR TITLE
Updating icons

### PR DESCRIPTION
**Pull request by samiyaakhtar**
- Changed yellow warning icon to red
- Changed the colors of red, yellow, gray, blue and green to match colors from this [page](https://projects.susielu.com/viz-palette?colors=%5B%22#2aa05b%22,%22%23e08a00%22,%22%23c8281f%22%5D&backgroundColor=%22white%22&fontColor=%22black%22&mode=%22normal%22).
... and other tasks under https://github.com/microsoft/bedrock/issues/1261 

Screen Shot 2020-03-30 at 11 44 47 AM

Screen Shot 2020-03-30 at 11 42 07 AM

Closes https://github.com/microsoft/bedrock/issues/1261

### CODE REVIEW

**Comment by gemorris** [comment]
In the second image, one of the red icons has an exclamation point, while the others have an X, what is the difference?

**Comment by samiyaakhtar** [comment]
@gemorris That one is a warning icon, it's showing up because that deployment has not failed but one of its builds have not started, so it's incomplete. As per our discussion we decided to turn it red, it was originally yellow. Does it make more sense to keep it yellow?

**Comment by gemorris** [comment]
Ahh, ok, I think I was mentally missing a status type

Success = Green
Failure = Red
Processing = Blue
Awaiting Approval = Yellow
Warning = Also Red

When you say one of its builds has not started, is this a status that would stick around until a human goes and fixes something, or it it temporary/the system keeps trying?  I am assuming this is different than the "awaiting approval" status?

**Comment by samiyaakhtar** [comment]
@gemorris So when a build has not started it could be one of these reasons: 

- it's going to start but hasn't started yet
- it has started but the task that sends data to spektate storage either hasn't run or the build failed _before_ that step was executed
- it is not going to start because the trigger conditions for this build pipeline were not met, this could happen when the previous build did not create a code change in the hld repo, for example. 
- it's waiting on a PR but the PR column is shown as empty in case the PR could not be fetched for whatever reason
- anything unknown. This is a default error case and if the status is not one of success, failure, processing, awaiting approval, then it will be unknown, hence "warning" in red

**Comment by gemorris** [comment]
Ok, so we need distinct colors and symbols for each status (and I missed a status type in our last meeting).

Assumptions:
Warning covers set of needs distinct from both "processing" and "failed"
Awaiting Approval is "less serious" than Warning
Warning is actionable, but Failed is not (?)

Let me know if any of these assumptions are not true.

Some alternatives (In order of preference):

1. Use purple for Awaiting Approval and Yellow for Warning
2. Reverse the Warning Icon (circle outline and exclamation point in red, not a distinct color but easier to differentiate).
3. Use Dark Gray for failed (if they truly aren't actionable)

**Comment by gemorris** [comment]
To be clear only one of those action items would need to be done. If they end up being appropriate.

**Comment by samiyaakhtar** [comment]
@gemorris 

1. I like the idea of using a different color for awaiting approval, since yellow is more like a color used for "information" rather than "you need to take an action here!". Do you have a specific purple you'd like me to use, since I don't see it on [this page](https://projects.susielu.com/viz-palette?colors=%5B%22#00bcf2%22,%22%233b606d%22,%22%23ef1674%22,%22%235b50e2%22,%22%23ffa929%22,%22%23ff4c39%22,%22%234bd78f%22,%22%23006627%22%5D&backgroundColor=%22%23323130%22&fontColor=%22%23ffffff%22&mode=%22normal%22)? 

2. This one might be hard to do with this react component since it has very limited icons, and the reversed warning icon is not available, unless we use the information icon which may be an "i"

3. Agreed that failed is not actionable, but should be visible enough for the user to know that something went wrong in a deployment and there may be something that needs to be fixed in the pipelines.

**Comment by gemorris** [comment]
In that case lets go with the purple. Please use #5b50e2 for now. I'm pulling from two different palettes so we may need to do some minor tweaking in the future, but at the moment I don't have time to make a new palette. :/

**Comment by samiyaakhtar** [comment]
@gemorris Sounds good, updated that. Do you think that the warning icon should go back to being yellow now, since there's no more a conflict with this purple one?

**Comment by samiyaakhtar** [comment]
Screen Shot 2020-03-31 at 11 50 06 AM

**Pull request merged**
